[project]
name = "dataset-ch-dav-flux-product"
version = "0.1.0"
description = ""
authors = [
    {name = "holukas@ethz.ch"}
]
readme = "README.md"
requires-python = ">=3.11,<3.12"
dependencies = [
    "jupyter-book (>=1.0.4.post1,<2.0.0)",
    "ghp-import (>=2.1.0,<3.0.0)",
    "sphinxcontrib-mermaid (>=1.0.0,<2.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.group.dev.dependencies]
diive = { path = "../../21 - DIIVE/diive", develop = true }
dbc-influxdb = { path = "../../22 - POET/dbc-influxdb", develop = true }
ghp-import = "^2.1.0"
jupyter-book = "^1.0.4.post1"
sphinxcontrib-mermaid = "^1.0.0"